<?php 
    $propiedades=[
                    [
                        "id"=>"1",
                        "imagen"=>"house1.jpg",
                        "nombre"=>"Casa Colina",
                        "estado"=>"disponible",
                        "tipo"=>"casa",
                        "ubicacion"=>"Heredia",
                        "direccion" => "300 metros sur del parque central de Santo Domingo",
                        "telefono" => "86352416",
                        "whatsapp" => "76543827",
                        "correo" => "ernestoulloa16@gmail.com",
                        "espaciosCochera" => 2,
                        "habitaciones"=>3,
                        "baños"=>2,
                        "precio"=>200000,
                    ],
                    [
                        "id"=>"2",
                        "imagen"=>"house2.jpg",
                        "nombre"=>"Casa Armonia",
                        "estado"=>"disponible",
                        "tipo"=>"casa",
                        "ubicacion"=>"Heredia",
                        "direccion" => "200 metros este de Ojo de agua",
                        "telefono" => "65142987",
                        "whatsapp" => "83752008",
                        "correo" => "mariaisabel_14@hotmail.es",
                        "espaciosCochera" => 3,
                        "habitaciones"=>4,
                        "baños"=>3,
                        "precio"=>500000,
                    ],
                    [
                        "id"=>"3",
                        "imagen"=>"house3.jpg",
                        "nombre"=>"Casa Montaña",
                        "estado"=>"disponible",
                        "tipo"=>"casa",
                        "ubicacion"=>"Alajuela",
                        "direccion" => "50 metros sur de la escuela Tranquilino Viquez",
                        "telefono" => "76834921",
                        "whatsapp" => "74389337",
                        "correo" => "luiscampos_71@gmail.com",
                        "espaciosCochera" => 2,
                        "habitaciones"=>3,
                        "baños"=>2,
                        "precio"=>150000,
                    ],
                    [
                    "id"=>"4",
                    "imagen"=>"house4.jpg",
                    "nombre"=>"Casa Paz",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"Heredia",
                    "direccion" => "Residencial el Castillo, Monte de la Cruz, Heredia",
                    "telefono" => "65142987",
                    "whatsapp" => "83752008",
                    "correo" => "mariaisabel_14@hotmail.es",
                    "espaciosCochera" => 2,
                    "habitaciones"=>3,
                    "baños"=>2,
                    "precio"=>170000,
                ],
                [
                    "id"=>"5",
                    "imagen"=>"house5.jpg",
                    "nombre"=>"Casa Colina",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"San Jose",
                    "direccion" => "Hacienda el Rey, Escazú, San Jose",
                    "telefono" => "76834921",
                    "whatsapp" => "74389337",
                    "correo" => "luiscampos_71@gmail.com",
                    "espaciosCochera" => 3,
                    "habitaciones"=>5,
                    "baños"=>4,
                    "precio"=>550000,
                ],
                [
                    "id"=>"6",
                    "imagen"=>"house6.jpg",
                    "nombre"=>"Casa La Hacienda",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"Alajuela",
                    "direccion" => "Residencial La Garita, La Garita, Alajuela",
                    "telefono" => "86352416",
                    "whatsapp" => "76543827",
                    "correo" => "ernestoulloa16@gmail.com", 
                    "espaciosCochera" => 2,
                    "habitaciones"=>3,
                    "baños"=>3,
                    "precio"=>210000,
                ],
                [
                    "id"=>"7",
                    "imagen"=>"house7.jpg",
                    "nombre"=>"Casa Castillo",
                    "estado"=>"vendido",
                    "tipo"=>"casa",
                    "ubicacion"=>"Heredia",
                    "direccion" => "Hacienda San Agustín, San Francisco, Herdia",
                    "telefono" => "86352416",
                    "whatsapp" => "76543827",
                    "correo" => "ernestoulloa16@gmail.com",
                    "espaciosCochera" => 2,
                    "habitaciones"=>4,
                    "baños"=>5,
                    "precio"=>400000,
                ],
                [
                    "id"=>"8",
                    "imagen"=>"house8.jpg",
                    "nombre"=>"Casa Rohrmoser",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"San Jose",
                    "direccion" => "400mts oeste de la torre Nunciatura, Rohrmoser",
                    "telefono" => "86352416",
                    "whatsapp" => "76543827",
                    "correo" => "ernestoulloa16@gmail.com",
                    "espaciosCochera" => 2,
                    "habitaciones"=>3,
                    "baños"=>2,
                    "precio"=>200000,
                ],
                [
                    "id"=>"9",
                    "imagen"=>"house9.jpg",
                    "nombre"=>"Casa Colón",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"San Jose",
                    "direccion" => "800mts este del parque de ciudad colón",
                    "telefono" => "76834921",
                    "whatsapp" => "74389337",
                    "correo" => "luiscampos_71@gmail.com",
                    "espaciosCochera" => 2,
                    "habitaciones"=>4,
                    "baños"=>4,
                    "precio"=>300000,
                ],
                [
                    "id"=>"10",
                    "imagen"=>"house10.jpg",
                    "nombre"=>"La paz",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"Alajuela",
                    "direccion" => "300 metros oeste de la finca UCR, Atenas",
                    "telefono" => "65142987",
                    "whatsapp" => "83752008",
                    "correo" => "mariaisabel_14@hotmail.es",
                    "espaciosCochera" => 3,
                    "habitaciones"=>4,
                    "baños"=>5,
                    "precio"=>400000,
                ],
                [
                    "id"=>"11",
                    "imagen"=>"house11.jpg",
                    "nombre"=>"Casa ciudad",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"Heredia",
                    "direccion" => "Condominio Tierras del Café, Heredia",
                    "telefono" => "65142987",
                    "whatsapp" => "83752008",
                    "correo" => "mariaisabel_14@hotmail.es",
                    "espaciosCochera" => 2,
                    "habitaciones"=>3,
                    "baños"=>2,
                    "precio"=>210000,
                ],
                [
                    "id"=>"12",
                    "imagen"=>"house12.jpg",
                    "nombre"=>"Casa La Guacima",
                    "estado"=>"disponible",
                    "tipo"=>"casa",
                    "ubicacion"=>"AlajuelaE",
                    "direccion" => "Residencial Hacienda los Reyes, Alajuela",
                    "telefono" => "86352416",
                    "whatsapp" => "76543827",
                    "correo" => "ernestoulloa16@gmail.com",
                    "espaciosCochera" => 2,
                    "habitaciones"=>3,
                    "baños"=>2,
                    "precio"=>200000,
                ],
                ]
?>

